# based on https://medium.com/chrisrbailey/github-actions-using-postgres-postgis-and-psql-e920a2aea7e1
name: Generate JSON tiles
on:
  workflow_dispatch:
jobs:
  run:
    name: Generate JSON tiles
    runs-on: ubuntu-latest
    env:
      REGION: Monaco
      POSTGRES_DSN: postgresql://postgres:password@localhost/osm 

    services:
      postgres:
        image: postgis/postgis:10-2.5
        env:
          # must specify password for PG Docker container image, see: https://registry.hub.docker.com/_/postgres?tab=description&page=1&name=10
          POSTGRES_PASSWORD: password
          POSTGRES_DB: osm
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout openscape
        uses: actions/checkout@v3
        with:
          repository: 'openscape-community/openscape'
      - name: Install dependencies
        run: |
          sudo apt install osmium-tool
          sudo mkdir -p /ingest/imposm3
          sudo chmod -R a+rw /ingest
          wget -q -O - https://github.com/omniscale/imposm3/releases/download/v0.11.1/imposm-0.11.1-linux-x86-64.tar.gz | \
            tar -xz --strip-components=1 -C /ingest/imposm3
          pip install pyrosm mercantile supermercado
      - name: Download pbf
        run: |
          echo PBF_PATH=$(python -c "from pyrosm import get_data; fp = get_data('$REGION'); print(fp)") >> "$GITHUB_ENV"
      - name: Import pbf
        run: |
          psql -d $POSTGRES_DSN -c "CREATE EXTENSION IF NOT EXISTS hstore"
          /ingest/imposm3/imposm import \
            -mapping svcs/data/soundscape/other/mapping.yml \
            -read /tmp/pyrosm/monaco-latest.osm.pbf \
            -write -connection postgis://postgres:password@localhost/osm  \
            -srid 4326
      - name: Install PostGIS functions
        run: |
          wget -q -O - https://raw.githubusercontent.com/mapbox/postgis-vt-util/master/postgis-vt-util.sql | \
            psql -d $POSTGRES_DSN
          psql -d $POSTGRES_DSN -f svcs/data/tilefunc.sql
      - name: Generate tiles
        run: |
          osmium export ${{ env.PBF_PATH }} -o ${{ env.PBF_PATH }}.geojson
          cat ${{ env.PBF_PATH }}.geojson | supermercado burn 16
